### ISSUE TITLE
catch-22 issue

### ISSUE THREAD

**Issue by nepeat** [voynix/spite-license#5]
by reading the license, how am I supposed to spread the word of this license? With the permission loss, I must spread the word of the license even though it is against the license's own terms to terminate usage of the materials? Worth it.

**Comment by voynix** [comment]
Per the README, the Spite License itself is released into the public domain.

The permission loss trapdoor thus only applies to software released under the Spite License, not the Spite License itself. 

You can use the Spite License to license your software, tell other people about it, and in general do whatever the heck you want with it, whether or not you've read the copy of the license in this repo.

Does this answer your question?
